import { Kontrak, Vendor } from './types';

export const kontrak: Kontrak[] = [
  {
    key: '1',
    namaPekerjaan: 'Implementasi e-Document Management System',
    subBidang: 'ERP Human Capital',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Ahmad Fauzi',
    pengawasPekerjaan: 'Nina Rachmawati',
    vendorKey: '1',
    vendorKHS: 'PT Akhdani Reka Solusi',
    nilaiTotal: 2000000000,
    nomorKontrak: 'K-A1312',
    nomorAmandemenKontrak: 'AM-2024-01',
    amandemenKontrakDetail: {
      nomorAmandemen: 'AM-2024-01',
      nomorKontrak: 'K-A1312',
      tanggal: '01/03/2024',
      deskripsi: 'Penambahan fitur dokumen OCR dan indexing otomatis.',
    },
    tanggalMulai: '05/01/2024',
    tanggalSelesai: '30/06/2024',
    terminPembayaran: 'Termin 3',
    infoStatusPembayaran: 'Terbayar Semua',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Terbayar', dokumen: ['kwitansi3.pdf'] },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '2',
    namaPekerjaan: 'Pemeliharaan Aplikasi HRIS 2024',
    subBidang: 'ERP Human Capital',
    tipePekerjaan: 'Pemeliharaan / Ophar',
    direksiPekerjaan: 'Rizal Maulana',
    pengawasPekerjaan: 'Dewi Lestari',
    vendorKey: '2',
    vendorKHS: 'PT Indocyber Global Teknologi (IGLO)',
    nilaiTotal: 1200000000,
    nomorKontrak: 'K-B7152',
    nomorAmandemenKontrak: '-',
    tanggalMulai: '01/02/2024',
    tanggalSelesai: '31/12/2024',
    terminPembayaran: 'Termin 1',
    infoStatusPembayaran: 'Terbayar Semua',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Terbayar', dokumen: ['kwitansi3.pdf'] },
      4: { status: 'Terbayar', dokumen: ['kwitansi4.pdf'] },
      5: { status: 'Terbayar', dokumen: ['kwitansi5.pdf'] },
      6: { status: 'Terbayar', dokumen: ['kwitansi6.pdf'] },
    },
    infoEvaluasi: 'Selesai',
  },
  {
    key: '3',
    namaPekerjaan: 'Pengembangan Modul e-Lelang Terintegrasi',
    subBidang: 'ERP Procurement & Logistic',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Dimas Saputra',
    pengawasPekerjaan: 'Tiara Anggraini',
    vendorKey: '3',
    vendorKHS: 'PT Duta Digital Nusantara (DDN)',
    nilaiTotal: 950000000,
    nomorKontrak: 'K-A1112',
    nomorAmandemenKontrak: 'REV-A1112',
    tanggalMulai: '10/03/2024',
    tanggalSelesai: '10/09/2024',
    terminPembayaran: 'Termin 3',
    infoStatusPembayaran: 'Terbayar Sebagian',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Belum Terbayar' },
      4: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '4',
    namaPekerjaan: 'Support & Maintenance Aplikasi Keuangan',
    subBidang: 'ERP Finance',
    tipePekerjaan: 'Pemeliharaan / Ophar',
    direksiPekerjaan: 'Bayu Pratama',
    pengawasPekerjaan: 'Laras Wulandari',
    vendorKey: '4',
    vendorKHS: 'PT Ecomindo Saranacipta (Ecomindo)',
    nilaiTotal: 800000000,
    nomorKontrak: 'K-C6001',
    nomorAmandemenKontrak: 'REV-C6001',
    tanggalMulai: '01/01/2024',
    tanggalSelesai: '31/12/2024',
    terminPembayaran: 'Termin 3',
    infoStatusPembayaran: 'Terbayar Sebagian',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Belum Terbayar' },
      4: { status: 'Belum Terbayar' },
      5: { status: 'Belum Terbayar' },
      6: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '5',
    namaPekerjaan: 'Pengembangan Sistem ERP Terintegrasi',
    subBidang: 'ERP Finance',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Siti Nurhaliza',
    pengawasPekerjaan: 'Rian Prasetyo',
    vendorKey: '1',
    vendorKHS: 'PT Akhdani Reka Solusi',
    nilaiTotal: 5000000000,
    nomorKontrak: 'K-D2401',
    nomorAmandemenKontrak: '-',
    tanggalMulai: '01/01/2024',
    tanggalSelesai: '31/12/2025',
    terminPembayaran: 'Termin 24',
    infoStatusPembayaran: 'Belum Terbayar Semua',
    dataStatusPembayaran: {
      1: { status: 'Belum Terbayar' },
      2: { status: 'Belum Terbayar' },
      3: { status: 'Belum Terbayar' },
      4: { status: 'Belum Terbayar' },
      5: { status: 'Belum Terbayar' },
      6: { status: 'Belum Terbayar' },
      7: { status: 'Belum Terbayar' },
      8: { status: 'Belum Terbayar' },
      9: { status: 'Belum Terbayar' },
      10: { status: 'Belum Terbayar' },
      11: { status: 'Belum Terbayar' },
      12: { status: 'Belum Terbayar' },
      13: { status: 'Belum Terbayar' },
      14: { status: 'Belum Terbayar' },
      15: { status: 'Belum Terbayar' },
      16: { status: 'Belum Terbayar' },
      17: { status: 'Belum Terbayar' },
      18: { status: 'Belum Terbayar' },
      19: { status: 'Belum Terbayar' },
      20: { status: 'Belum Terbayar' },
      21: { status: 'Belum Terbayar' },
      22: { status: 'Belum Terbayar' },
      23: { status: 'Belum Terbayar' },
      24: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '6',
    namaPekerjaan: 'Pembuatan Dashboard Monitoring Pelanggan',
    subBidang: 'Distribusi & Pelayanan Pelanggan',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Wahyu Ramadhan',
    pengawasPekerjaan: 'Intan Permata',
    vendorKey: '4',
    vendorKHS: 'PT Ecomindo Saranacipta (Ecomindo)',
    nilaiTotal: 1500000000,
    nomorKontrak: 'K-E1001',
    nomorAmandemenKontrak: '-',
    tanggalMulai: '01/04/2024',
    tanggalSelesai: '01/10/2024',
    terminPembayaran: 'Termin 4',
    infoStatusPembayaran: 'Terbayar Sebagian',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Belum Terbayar' },
      4: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '7',
    namaPekerjaan: 'Pengembangan Sistem Pemantauan Proyek Pembangkit',
    subBidang: 'Proyek, Pembangkit & Transmisi',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Arief Wijaya',
    pengawasPekerjaan: 'Putri Aisyah',
    vendorKey: '5',
    vendorKHS: 'PT Gits Indonesia',
    nilaiTotal: 3200000000,
    nomorKontrak: 'K-F3202',
    nomorAmandemenKontrak: '-',
    tanggalMulai: '01/05/2024',
    tanggalSelesai: '31/12/2024',
    terminPembayaran: 'Termin 6',
    infoStatusPembayaran: 'Belum Terbayar Semua',
    dataStatusPembayaran: {
      1: { status: 'Belum Terbayar' },
      2: { status: 'Belum Terbayar' },
      3: { status: 'Belum Terbayar' },
      4: { status: 'Belum Terbayar' },
      5: { status: 'Belum Terbayar' },
      6: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
  {
    key: '8',
    namaPekerjaan: 'Pengembangan Platform Analitik Distribusi Listrik',
    subBidang: 'Data Analitik & Geospasial',
    tipePekerjaan: 'Pengembangan / Change Request',
    direksiPekerjaan: 'Hafiz Ramdani',
    pengawasPekerjaan: 'Aulia Zahra',
    vendorKey: '6',
    vendorKHS: 'PT Walden Global Services',
    nilaiTotal: 2700000000,
    nomorKontrak: 'K-G9009',
    nomorAmandemenKontrak: '-',
    tanggalMulai: '01/03/2024',
    tanggalSelesai: '01/09/2024',
    terminPembayaran: 'Termin 5',
    infoStatusPembayaran: 'Terbayar Sebagian',
    dataStatusPembayaran: {
      1: { status: 'Terbayar', dokumen: ['kwitansi1.pdf'] },
      2: { status: 'Terbayar', dokumen: ['kwitansi2.pdf'] },
      3: { status: 'Terbayar', dokumen: ['kwitansi3.pdf'] },
      4: { status: 'Belum Terbayar' },
      5: { status: 'Belum Terbayar' },
    },
    infoEvaluasi: 'Belum Selesai',
  },
];

export const vendor: Vendor[] = [
  {
    key: '1',
    namaVendor: 'PT Akhdani Reka Solusi',
    nilaiKeseluruhan: 92,
    evaluasiVendor: 4.6,
    suratPeringatan: 'Ada',
    totalProyek: 3,
    suratPeringatanDetail: [
      {
        nomor: 'SP/003/AKD/2024',
        tanggal: '2024-06-18',
        alasan: 'Tidak memenuhi SLA dalam pengembangan modul pelaporan.',
      },
    ],
  },
  {
    key: '2',
    namaVendor: 'PT Indocyber Global Teknologi',
    nilaiKeseluruhan: 88,
    evaluasiVendor: 4.3,
    suratPeringatan: 'Tidak ada',
    totalProyek: 2,
  },
  {
    key: '3',
    namaVendor: 'PT Duta Digital Nusantara',
    nilaiKeseluruhan: 85,
    evaluasiVendor: 4.2,
    suratPeringatan: 'Ada',
    totalProyek: 2,
    suratPeringatanDetail: [
      {
        nomor: 'SP/001/DDN/2024',
        tanggal: '2024-05-10',
        alasan: 'Keterlambatan penyampaian deliverable fase UAT.',
      },
    ],
  },
  {
    key: '4',
    namaVendor: 'PT Ecomindo Saranacipta',
    nilaiKeseluruhan: 78,
    evaluasiVendor: 3.9,
    suratPeringatan: 'Ada',
    totalProyek: 1,
    suratPeringatanDetail: [
      {
        nomor: 'SP/002/ECOM/2024',
        tanggal: '2024-04-22',
        alasan: 'Kualitas dokumentasi tidak sesuai standar PLN.',
      },
    ],
  },
  {
    key: '5',
    namaVendor: 'PT Gits Indonesia',
    nilaiKeseluruhan: 81,
    evaluasiVendor: 4.0,
    suratPeringatan: 'Tidak ada',
    totalProyek: 1,
  },
  {
    key: '6',
    namaVendor: 'PT Walden Global Services',
    nilaiKeseluruhan: 87,
    evaluasiVendor: 4.4,
    suratPeringatan: 'Tidak ada',
    totalProyek: 1,
  },
];
