[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"           # web framework
serde = { version = "1.0", features = ["derive"] }  # serialization/deserialization
serde_json = "1.0"        # JSON support
